# Generated by Django 5.1.7 on 2025-03-30 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_sectionimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='image',
        ),
    ]
