# Generated by Django 5.1.7 on 2025-03-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0003_remove_section_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionimage',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
