# Generated by Django 5.1.7 on 2025-03-31 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0004_sectionimage_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='description',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='image',
        ),
        migrations.AlterField(
            model_name='chef',
            name='bafouille',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chef',
            name='totem',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
