# Generated by Django 5.1.7 on 2025-03-31 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0005_remove_staff_description_remove_staff_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chef',
            name='staff',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
