# Generated by Django 5.1.7 on 2025-03-31 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0006_remove_chef_staff_delete_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sections.section'),
        ),
    ]
