# Generated by Django 5.1.7 on 2025-03-31 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0007_chef_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sections.section'),
        ),
    ]
