# Generated by Django 5.1.7 on 2025-03-31 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0008_alter_chef_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='ChefImage',
        ),
    ]
