# Generated by Django 5.1.7 on 2025-03-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0009_chef_image_delete_chefimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chef',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='nom',
            new_name='name',
        ),
        migrations.AddField(
            model_name='section',
            name='bank_account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='filled',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
