# Generated by Django 5.1.7 on 2025-03-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0010_rename_nom_chef_name_rename_nom_section_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='bank_account',
            new_name='bankAccount',
        ),
        migrations.AddField(
            model_name='chef',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
