# Generated by Django 5.1.7 on 2025-04-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0011_rename_bank_account_section_bankaccount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='uniformDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='uniformImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
