# Generated by Django 5.1.7 on 2025-04-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0012_section_uniformdescription_section_uniformimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='staffImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
