# Generated by Django 5.1.7 on 2025-04-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0014_rename_staffimage_section_sectionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
