# Generated by Django 5.1.7 on 2025-04-18 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0015_section_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='sectionImage',
            new_name='showcaseImage',
        ),
    ]
