# Generated by Django 5.1.7 on 2025-04-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0016_rename_sectionimage_section_showcaseimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chefs-images/'),
        ),
        migrations.AlterField(
            model_name='sectionimage',
            name='image',
            field=models.ImageField(upload_to='sections-images/'),
        ),
    ]
