# Generated by Django 5.1.7 on 2025-04-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0017_alter_chef_image_alter_sectionimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='showcaseImage',
            field=models.ImageField(blank=True, null=True, upload_to='sections-images/'),
        ),
        migrations.AlterField(
            model_name='section',
            name='uniformImage',
            field=models.ImageField(blank=True, null=True, upload_to='uniformes-images/'),
        ),
    ]
