# Generated by Django 6.0.4 on 2026-04-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0018_alter_section_showcaseimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='chefResp',
            field=models.BooleanField(default=False, verbose_name='Chef responsable'),
        ),
        migrations.AddConstraint(
            model_name='chef',
            constraint=models.UniqueConstraint(condition=models.Q(('chefResp', True)), fields=('section',), name='unique_chef_resp_per_section'),
        ),
    ]
