version: '3.9'

services:
  db:
    image: postgres:15
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - mynetwork

  backend:
    build: ./backend
    command: ./entrypoint.sh
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - mynetwork

  frontend:
    build: ./frontend
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./frontend:/app
    ports:
      - 5173:5173
    depends_on:
      - backend
    networks:
      - mynetwork

volumes:
  pgdata:

networks:
  mynetwork:
