version: '3.9'

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    command: pipenv run gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    expose:
      - 8000
    env_file:
      - .env.prod
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile.prod
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
