# Generated by Django 5.1.7 on 2025-04-11 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_event_location_alter_event_description'),
        ('sections', '0014_rename_staffimage_section_sectionimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sections.section'),
        ),
    ]
