# Generated by Django 5.1.7 on 2025-04-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_alter_event_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='highlight',
            field=models.BooleanField(default=False),
        ),
    ]
