# Generated by Django 5.1.7 on 2025-04-28 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_agenda'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agenda',
            new_name='AgendaDocument',
        ),
    ]
