# Generated by Django 5.1.7 on 2025-04-29 11:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_rename_agenda_agendadocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendadocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendadocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
