# Generated by Django 5.1.7 on 2025-04-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='infos-images/'),
        ),
        migrations.AddField(
            model_name='info',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='infos-videos/'),
        ),
    ]
