# Generated by Django 5.1.7 on 2025-04-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0002_info_image_info_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
