# Generated by Django 5.1.7 on 2025-04-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0004_rename_link_info_videolink'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='link',
            field=models.URLField(blank=True, help_text="Permet de mettre un lien vers une page d'information et de l'afficher sur le site.", null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='video',
            field=models.FileField(blank=True, help_text="Permet de uploader une vidéo et de l'afficher sur le site.", null=True, upload_to='infos-videos/'),
        ),
        migrations.AlterField(
            model_name='info',
            name='videoLink',
            field=models.URLField(blank=True, help_text="Permet de mettre un lien vidéo (YouTube ou autre) et de l'afficher sur le site. (Ne permet pas d'uploader une vidéo)", null=True),
        ),
    ]
