# Generated by Django 5.1.7 on 2025-04-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0005_info_link_alter_info_video_alter_info_videolink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='videoLink',
            field=models.CharField(blank=True, help_text="Permet de mettre un lien vidéo (YouTube ou autre) et de l'afficher sur le site. (Ne permet pas d'uploader une vidéo)", max_length=1000, null=True),
        ),
    ]
