# Generated by Django 5.2 on 2025-04-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0006_alter_info_videolink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
