# Generated by Django 5.1.7 on 2025-04-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio_camp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiocamp',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
