# Generated by Django 5.1.7 on 2025-04-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio_camp', '0002_radiocamp_password'),
        ('sections', '0016_rename_sectionimage_section_showcaseimage'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='radiocamp',
            constraint=models.UniqueConstraint(fields=('section',), name='unique_section_radiocamp'),
        ),
    ]
