# Generated by Django 5.1.7 on 2025-04-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accueilitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accueilitem',
            name='titre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
