# Generated by Django 5.1.7 on 2025-04-29 11:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0002_alter_accueilitem_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accueilitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accueilitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
