# Generated by Django 5.2 on 2025-05-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0004_accueilbutton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accueilbutton',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
